theme: jekyll-theme-minimal
title: Shashank Bangalore Lakshman
description: Engineering Leader in Machine Learning + Semiconductors
logo: /assets/img/logo.png
show_downloads: false
google_analytics: UA-158110477-1
