theme: jekyll-theme-minimal
title: The world is my sandbox
description: Engineering experiences of Shashank Bangalore Lakshman
logo: /assets/img/logo.png
show_downloads: false
google_analytics: UA-158110477-1
